### ISSUE TITLE
Add issue and pr template

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#11]
hack content from https://github.com/commaai/openpilot/tree/master/.github

- [ ] `config.yml`

```
blank_issues_enabled: false
contact_links:
  - name: Public AMA
    url: https://twitter.com/intent/follow?screen_name=flexbox_
    about: For open questions and discussion
  - name: Slack Community
    url: https://weblille.rocks/
    about: Our french programming and indie hackers community
```
