### ISSUE TITLE
graphql codegen

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#150]
As a dev
I can automatically generate types 
So that i can work faster

---

- [ ] watch this https://www.youtube.com/watch?v=rT_jKDNMgRw
- [ ] setup guide https://the-guild.dev/graphql/codegen/docs/getting-started/installation#initialization-wizard
- [ ] Nx GraphQL setup "Setup React Code Generation" https://blog.nrwl.io/using-apollo-graphql-with-react-in-an-nx-workspace-99db8d69cebe

I have this error 

![CleanShot 2024-03-02 at 14 49 35@2x](https://github.com/flexbox/weshipit.today/assets/360936/7b9c3347-5950-47d3-83fc-e8587e477b6f)

with `codegen.yml`

```yml
overwrite: true
schema: 'http://localhost:5005/api/airtable/__graphql'
documents: 'apps/weshipit/stepzen/airtable.graphql'
generates:
  apps/weshipit/stepzen/generated/graphql.ts:
    plugins:
      - 'typescript-react-apollo'
      - 'typescript-graphql-files-modules'
      - 'fragment-matcher'
  ./graphql.schema.json:
    plugins:
      - 'introspection'

```

**Comment by flexbox** [comment]
![CleanShot 2024-03-15 at 21 44 59@2x](https://github.com/flexbox/weshipit.today/assets/360936/adaf38cd-8439-47f3-b2d5-f031944b4a35)

```yml
overwrite: true
schema: 'http://localhost:5005/api/airtable/__graphql'
documents: 'apps/weshipit/stepzen/index.graphql'
generates:
  apps/weshipit/stepzen/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      withComponent: false
      withHOC: false

```
